import WorkFlow

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

private var number: Int = 0

class FakeWorkFlowComponent : WorkFlowComponent, Equatable, CustomDebugStringConvertible {
    fileprivate let hash: Int

    var debugDescription: String {
        return "FakeWorkFlowComponent - \(hash)"
    }

    init() {
        self.hash = number
        number += 1
    }

    fileprivate(set) var beginWorkCallCount : Int = 0
    fileprivate var beginWorkArgs : Array<(WorkFlowFinishCallback)> = []
    func beginWorkArgsForCall(_ callIndex: Int) -> (WorkFlowFinishCallback) {
        return self.beginWorkArgs[callIndex]
    }
    func beginWork(_ callback: WorkFlowFinishCallback) {
        self.beginWorkCallCount += 1
        self.beginWorkArgs.append(callback)
    }

    static func reset() {
    }
}

func ==(a: FakeWorkFlowComponent, b: FakeWorkFlowComponent) -> Bool {
    return a.hash == b.hash
}
